version: '3'
services:
  maplestory:
    build: .
    depends_on:
      - db
    ports:
      - "8484:8484"
      - "7575-7577:7575-7577"
    volumes:
      - ./config.yaml:/opt/server/config.yaml
      - ./scripts:/opt/server/scripts
      - ./wz:/opt/server/wz
    environment:
      DB_HOST: "db"

  db:
    image: mysql:8.4.0
    environment:
      MYSQL_DATABASE: "cosmic"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    ports:
      - "3307:3306"
    volumes:
      - ./database/docker-db-data:/var/lib/mysql

  web:
    build: ./web
    depends_on:
      - db
      - maplestory
    ports:
      - "3000:3000"
    volumes:
      - ./handbook:/handbook
    environment:
      DATABASE_URL: "mysql://root:@db:3306/cosmic"
      NEXTAUTH_SECRET: "dev-secret-do-not-use-in-prod"
      NEXTAUTH_URL: "http://127.0.0.1:3000"
      GAME_SERVER_HOST: "maplestory"
      GAME_LOGIN_PORT: "8484"
      NEXT_PUBLIC_SITE_URL: "http://127.0.0.1:3000"
